spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}

cors:
  allowed-origins:
    - "https://your-app-name.vercel.app"
    - "http://localhost:3000"