spring:
  application:
    name: banking-backend
  flyway:
    enabled: true
    # locations: classpath:db/migration # If necessary.
    baseline-on-migrate: true
    baseline-version: 1
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl:
      auto: update
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 600 # 10 minutes
    refreshTokenExpiration: 604800 # 7 days
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include=health: