spring:
  datasource:
    # Option 1: Transform DATABASE_URL by replacing postgresql:// with jdbc:postgresql://
    url: jdbc:${DATABASE_URL/postgresql:/postgresql:}
    driver-class-name: org.postgresql.Driver

    # Connection pool settings for Railway
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  # Flyway configuration
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${PORT:8080}

cors:
  allowed-origins:
    - "https://your-app-name.vercel.app"
    - "http://localhost:3000"

# Logging for debugging (remove in production)
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG