spring:
  application:
    name: banking-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER:bankingapp}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl:
      auto: update