spring:
  application:
    name: banking-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER:bankingapp}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl:
      auto: update
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5 minutes
    refreshTokenExpiration: 604800 # 7 days
  flyway:
    enabled: true
    # locations: classpath:db/migration # If necessary.
    baseline-on-migrate: true
    baseline-version: 1